"""
Model Training and Evaluation
Early-Stage Diabetes Risk Prediction System

Trains and evaluates four classification models:
- Logistic Regression
- Random Forest
- XGBoost
- Support Vector Machine (SVM)
"""

from pathlib import Path
import json

import joblib
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    auc,
    classification_report,
    f1_score,
    precision_score,
    recall_score,
    roc_curve,
)
from sklearn.svm import SVC
from xgboost import XGBClassifier


DATA_DIR = Path("data")
RESULTS_DIR = Path("results")


def load_training_data():
    """Load processed train/test splits generated by preprocessing pipeline."""
    X_train_path = DATA_DIR / "X_train.csv"
    X_test_path = DATA_DIR / "X_test.csv"
    y_train_path = DATA_DIR / "y_train.csv"
    y_test_path = DATA_DIR / "y_test.csv"

    X_train = pd.read_csv(X_train_path)
    X_test = pd.read_csv(X_test_path)
    y_train = pd.read_csv(y_train_path).squeeze("columns")
    y_test = pd.read_csv(y_test_path).squeeze("columns")

    return X_train, X_test, y_train, y_test


def build_models():
    """Return configured model instances."""
    return {
        "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
        "Random Forest": RandomForestClassifier(
            n_estimators=300, max_depth=None, min_samples_split=4, random_state=42
        ),
        "XGBoost": XGBClassifier(
            n_estimators=300,
            learning_rate=0.05,
            max_depth=4,
            subsample=0.9,
            colsample_bytree=0.9,
            objective="binary:logistic",
            eval_metric="logloss",
            random_state=42,
        ),
        "SVM": SVC(kernel="rbf", C=1.0, gamma="scale", probability=True, random_state=42),
    }


def evaluate_model(name, model, X_test, y_test):
    """Evaluate model and return metrics and ROC curve data."""
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:, 1]

    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    accuracy = accuracy_score(y_test, y_pred)

    fpr, tpr, _ = roc_curve(y_test, y_prob)
    roc_auc = auc(fpr, tpr)

    metrics = {
        "model": name,
        "accuracy": float(accuracy),
        "precision": float(precision),
        "recall": float(recall),
        "f1_score": float(f1),
        "auc_roc": float(roc_auc),
    }
    report = classification_report(y_test, y_pred)

    return metrics, report, fpr, tpr


def save_comparison_chart(results_df):
    """Save grouped bar chart for primary metrics."""
    sns.set_style("whitegrid")
    plot_df = results_df.melt(
        id_vars="model", value_vars=["accuracy", "precision", "recall", "f1_score"], var_name="metric", value_name="score"
    )

    plt.figure(figsize=(12, 6))
    sns.barplot(data=plot_df, x="model", y="score", hue="metric")
    plt.ylim(0, 1.0)
    plt.title("Model Performance Comparison")
    plt.xlabel("Model")
    plt.ylabel("Score")
    plt.legend(title="Metric")
    plt.tight_layout()
    out_path = RESULTS_DIR / "model_comparison.png"
    plt.savefig(out_path, dpi=300, bbox_inches="tight")
    plt.close()
    print(f"Saved: {out_path}")


def save_roc_curves(roc_curves):
    """Save ROC curve comparison plot."""
    plt.figure(figsize=(9, 7))
    for name, (fpr, tpr, roc_auc) in roc_curves.items():
        plt.plot(fpr, tpr, lw=2, label=f"{name} (AUC={roc_auc:.3f})")

    plt.plot([0, 1], [0, 1], linestyle="--", color="gray", label="Random baseline")
    plt.xlim(0.0, 1.0)
    plt.ylim(0.0, 1.05)
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.title("ROC Curves - Model Comparison")
    plt.legend(loc="lower right")
    plt.tight_layout()
    out_path = RESULTS_DIR / "roc_curves.png"
    plt.savefig(out_path, dpi=300, bbox_inches="tight")
    plt.close()
    print(f"Saved: {out_path}")


def save_feature_importance(best_name, best_model, feature_names):
    """Save feature importance plot for models that support it."""
    importances = None

    if hasattr(best_model, "feature_importances_"):
        importances = best_model.feature_importances_
    elif hasattr(best_model, "coef_"):
        importances = abs(best_model.coef_[0])

    if importances is None:
        print(f"Skipping feature importance for {best_name}: not supported.")
        return

    fi = pd.DataFrame({"feature": feature_names, "importance": importances}).sort_values(
        by="importance", ascending=False
    )

    plt.figure(figsize=(10, 6))
    sns.barplot(data=fi.head(12), x="importance", y="feature", color="steelblue")
    plt.title(f"Top Feature Importance - {best_name}")
    plt.xlabel("Importance")
    plt.ylabel("Feature")
    plt.tight_layout()
    out_path = RESULTS_DIR / "feature_importance.png"
    plt.savefig(out_path, dpi=300, bbox_inches="tight")
    plt.close()
    print(f"Saved: {out_path}")


def main():
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)

    print("\n" + "=" * 70)
    print("EARLY-STAGE DIABETES RISK PREDICTION")
    print("Model Training and Evaluation")
    print("=" * 70)

    X_train, X_test, y_train, y_test = load_training_data()
    models = build_models()

    all_metrics = []
    roc_curves = {}

    for name, model in models.items():
        print("\n" + "-" * 70)
        print(f"Training: {name}")
        model.fit(X_train, y_train)

        metrics, report, fpr, tpr = evaluate_model(name, model, X_test, y_test)
        all_metrics.append(metrics)
        roc_curves[name] = (fpr, tpr, metrics["auc_roc"])

        model_path = RESULTS_DIR / f"{name.lower().replace(' ', '_')}.pkl"
        joblib.dump(model, model_path)
        print(f"Saved model: {model_path}")
        print(report)

    results_df = pd.DataFrame(all_metrics).sort_values(by="auc_roc", ascending=False).reset_index(drop=True)
    results_path = RESULTS_DIR / "model_metrics.csv"
    results_df.to_csv(results_path, index=False)

    with open(RESULTS_DIR / "model_metrics.json", "w", encoding="utf-8") as f:
        json.dump(all_metrics, f, indent=2)

    print("\n" + "=" * 70)
    print("MODEL COMPARISON TABLE")
    print("=" * 70)
    print(results_df)
    print(f"\nSaved: {results_path}")

    save_comparison_chart(results_df)
    save_roc_curves(roc_curves)

    best_model_name = results_df.iloc[0]["model"]
    best_model_path = RESULTS_DIR / f"{best_model_name.lower().replace(' ', '_')}.pkl"
    best_model = joblib.load(best_model_path)
    save_feature_importance(best_model_name, best_model, X_train.columns.tolist())

    print("\n" + "=" * 70)
    print(f"Best model by AUC-ROC: {best_model_name}")
    print("=" * 70 + "\n")


if __name__ == "__main__":
    main()
